name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  test:
    runs-on: 
    defaults:
      run:
        working-directory: typescript/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install 
      - name: Run Unit Tests
        run: npm run test
  stryker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: typescript/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install 
      - name: Run Stryker
        run: npm run mutation